# Aider configuration for NapkinWire project
# Uses OpenRouter with free tier models to preserve Claude usage

# OpenRouter configuration
model: openrouter/qwen/qwen-2.5-coder-32b-instruct
api_base: https://openrouter.ai/api/v1
openrouter_api_key: ${OPENROUTER_API_KEY}

# Alternative free models to try if primary fails:
# - openrouter/microsoft/phi-3-mini-128k-instruct:free
# - openrouter/google/gemma-2-9b-it:free
# - openrouter/meta-llama/llama-3.2-3b-instruct:free
# - openrouter/deepseek/deepseek-coder-6.7b-base:free

# Aider behavior settings
auto_commits: true
dirty_commits: false
git: true
voice: false
pretty: true
stream: true

# Development settings
show_diffs: true
editor: code
dark_mode: auto

# File handling
include:
  - "mcp/*.py"
  - "web/*.js"
  - "web/*.html"
  - "*.md"
  - "*.yml"
  - "*.yaml"

exclude:
  - "__pycache__/"
  - "*.pyc"
  - ".git/"
  - "node_modules/"
  - "venv/"
  - ".venv/"